# Generated by Django 2.0.10 on 2019-09-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zjvapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='text',
            new_name='description',
        ),
    ]
